[package]
name = "bevy_mod_picking"
version = "0.20.0-rc.0"
authors = ["Aevyrie <aevyrie@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
description = "A modular picking plugin for Bevy."
repository = "https://github.com/aevyrie/bevy_mod_picking/"
keywords = ["gamedev", "picking", "bevy", "input", "eventlistener"]
categories = ["game-engines", "rendering"]
resolver = "2"
rust-version = "1.76.0"

[package.metadata.docs.rs]
all-features = true


[workspace]
members = ["crates/*", "backends/*"]

[dependencies]
bevy_app = { git = "https://github.com/bevyengine/bevy.git", default-features = false }
bevy_core = { git = "https://github.com/bevyengine/bevy.git", default-features = false }
bevy_core_pipeline = { git = "https://github.com/bevyengine/bevy.git", optional = true, default-features = false }
bevy_ecs = { git = "https://github.com/bevyengine/bevy.git", default-features = false }
bevy_math = { git = "https://github.com/bevyengine/bevy.git", default-features = false }
bevy_reflect = { git = "https://github.com/bevyengine/bevy.git", default-features = false }
bevy_render = { git = "https://github.com/bevyengine/bevy.git", default-features = false }
bevy_text = { git = "https://github.com/bevyengine/bevy.git", optional = true, default-features = false, features = [
    "default_font",
] }
bevy_utils = { git = "https://github.com/bevyengine/bevy.git", default-features = false }
bevy_window = { git = "https://github.com/bevyengine/bevy.git", default-features = false }

# Optional
bevy_color = { git = "https://github.com/bevyengine/bevy.git", optional = true, default-features = false }
bevy_ui = { git = "https://github.com/bevyengine/bevy.git", optional = true, default-features = false }

bevy_eventlistener = { git = "https://github.com/iancormac84/bevy_eventlistener.git", branch = "bevy-main" }
bevy_egui = { optional = true, version = ">=0.25,  <=0.27" }
bevy_rapier3d = { optional = true, version = ">=0.25, <=0.26" }
bevy_xpbd_3d = { optional = true, version = "0.4" }

# Local
bevy_picking_core = { path = "crates/bevy_picking_core", version = "0.20.0-rc.0" }
bevy_picking_input = { path = "crates/bevy_picking_input", version = "0.20.0-rc.0" }
bevy_picking_selection = { optional = true, path = "crates/bevy_picking_selection", version = "0.20.0-rc.0" }
bevy_picking_highlight = { optional = true, path = "crates/bevy_picking_highlight", version = "0.20.0-rc.0" }
bevy_picking_raycast = { optional = true, path = "backends/bevy_picking_raycast", version = "0.20.0-rc.0" }
bevy_picking_ui = { optional = true, path = "backends/bevy_picking_ui", version = "0.20.0-rc.0" }
bevy_picking_rapier = { optional = true, path = "backends/bevy_picking_rapier", version = "0.20.0-rc.0" }
bevy_picking_sprite = { optional = true, path = "backends/bevy_picking_sprite", version = "0.20.0-rc.0" }
bevy_picking_egui = { optional = true, path = "backends/bevy_picking_egui", version = "0.20.0-rc.0" }
bevy_picking_xpbd = { optional = true, path = "backends/bevy_picking_xpbd", version = "0.20.0-rc.0" }

[dev-dependencies]
bevy = { git = "https://github.com/bevyengine/bevy.git", default-features = false, features = [
    "bevy_winit",
    "x11",
    "bevy_gltf",
    "bevy_scene",
    "bevy_ui",
    "bevy_gizmos",
    "png",
    "ktx2",
    "zstd",
    "tonemapping_luts",
] }

[features]
all = [
    "selection",
    "highlight",
    "debug",
    "backend_raycast",
    "backend_bevy_ui",
    "backend_rapier",
    "backend_sprite",
    "backend_egui",
    "backend_xpbd",
]
default = [
    "backend_raycast",
    "backend_bevy_ui",
    "backend_sprite",
    "debug",
    "selection",
    "highlight",
]
selection = [
    "bevy_picking_selection",
    "bevy_picking_input/selection",
    "bevy_picking_highlight/selection",
]
highlight = ["bevy_picking_highlight/pbr"]
debug = ["bevy_text", "bevy_ui/bevy_text", "bevy_core_pipeline"]
backend_raycast = ["bevy_picking_raycast"]
backend_rapier = ["bevy_picking_rapier", "bevy_rapier3d"]
backend_sprite = ["bevy_picking_sprite", "bevy_picking_highlight/sprite"]
backend_bevy_ui = ["bevy_picking_ui", "bevy_ui", "bevy_color"]
backend_egui = ["bevy_picking_egui", "bevy_egui"]
backend_xpbd = ["bevy_picking_xpbd", "bevy_xpbd_3d"]

[[example]]
name = "rapier"
path = "examples/rapier.rs"
required-features = ["backend_rapier"]

[[example]]
name = "egui"
path = "examples/egui.rs"
required-features = ["backend_egui"]

[[example]]
name = "event_listener"
path = "examples/event_listener.rs"
required-features = ["backend_egui"]

[[example]]
name = "render_to_texture"
path = "examples/render_to_texture.rs"
required-features = ["bevy_egui"]

[[example]]
name = "split_screen"
path = "examples/split_screen.rs"
required-features = ["backend_egui"]

[[example]]
name = "xpbd"
path = "examples/xpbd.rs"
required-features = ["backend_xpbd"]
